name: my_portfolio
description: my portfolio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  google_fonts: ^2.1.1
  flutter_svg: ^1.0.0
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.0
  mqtt_client: ^9.6.3
  intl: ^0.17.0
  desktop_drop: ^0.3.2
  #args:
   # git:
    #  url: git://github.com/simonmdsn/args.git

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
